fix can't use function return value in write context
Fixes:

Fatal error: Can't use function return value in write context in
/var/www/site.com/wp-content/plugins/fb-instant-articles/wizard/template
s/wizard-template.php on line 101

Causes the edit screen not to show, empty() prefers variable not
function